version: '3.8'

services:
  redis:
    image: redis:alpine
    # networks:
    #   - app-network

#   db:
#     image: postgres:13-alpine
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - app-network

#   backend:
#     build: ./backend
#     command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
#     environment:
#       DB_HOST: db
#       DB_NAME: ${DB_NAME}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       SECRET_KEY: ${SECRET_KEY}
#     depends_on:
#       - db
#       - redis
#     networks:
#       - app-network

#   frontend:
#     build: ./frontend
#     environment:
#       NUXT_HOST: 0.0.0.0
#       NUXT_PORT: 3000
#       API_URL: http://backend:8000/api/v1
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   celery:
#     build: ./backend
#     command: celery -A config worker -l info
#     depends_on:
#       - backend
#       - redis
#     environment:
#       DB_HOST: db
#       DB_NAME: ${DB_NAME}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       SECRET_KEY: ${SECRET_KEY}
#     networks:
#       - app-network

# volumes:
#   postgres_data:

# networks:
#   app-network:
#     driver: bridge