# Generated by Django 5.1.8 on 2025-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.ImageField(upload_to='trips/'),
        ),
    ]
